var CONSTS = {
    HOURS_PER_WEEK: 45,
    HOURS_PER_MONTH: 180,
    ONE_DAY: 24 * 60 * 60 * 1000,
    ONE_HOUR: 60 * 60 * 1000,
    UNKNOWN_ROLE: 'unknown_role',
    UNDETERMINED_ROLE: 'undetermined_role',
    UNSPECIFIED: 'Unspecified',
    
    VIEW_TASKS_PERMISSION: "viewTasks",
    EDIT_TASKS_PERMISSION: "editTasks",
    VIEW_ASSIGNMENTS_PERMISSION: "viewAssignments",
    EDIT_ASSIGNMENTS_PERMISSION: "editAssignments",
    VIEW_CONFIGURATION_PERMISSION: "viewConfiguration",
    EDIT_CONFIGURATION_PERMISSION: "editConfiguration",
    VIEW_HOURS_PERMISSION: "viewHours",
    EDIT_HOURS_PERMISSION: "editHours",
    DELETE_MY_HOURS_PERMISSION: "deleteMyHours",
    EDIT_MY_HOURS_PERMISSION: "editMyHours",
    VIEW_HOURS_REPORTS_CSV_PERMISSION: "viewHoursReportsAndCSV",
    VIEW_PEOPLE: "viewPeople",
    VIEW_PROFILE: "viewProfile",
    EDIT_PROFILE: "editProfile",
    VIEW_MY_PROFILE: "viewMyProfile",
    EDIT_MY_PROFILE: "editMyProfile",
    VIEW_PERSONNEL_DATA: "viewPersonnelData",
    EDIT_PERSONNEL_DATA: "editPersonnelData",
    VIEW_GROUPS: "viewGroups",
    EDIT_GROUPS: "editGroups",
    VIEW_PROJECTS: "viewProjects",
    EDIT_PROJECTS: "editProjects",
    DELETE_PROJECTS: "deleteProjects",
    VIEW_PROJECT_LINKS: "viewProjectLinks",
    EDIT_PROJECT_LINKS: "editProjectLinks",
    VIEW_ROLES: "viewRoles",
    EDIT_ROLES: "editRoles",
    VIEW_VACATIONS: "viewVacations",
    VIEW_MY_VACATIONS: "viewMyVacations",
    EDIT_VACATIONS: "editVacations",
    EDIT_MY_VACATIONS: "editMyVacations",
    VIEW_NOTIFICATIONS: "viewNotifications",
    EDIT_NOTIFICATIONS: "editNotifications",
    DELETE_NOTIFICATIONS: "deleteNotifications", 
    EXECUTE_UPGRADE: "executeUpgrade",
    VIEW_SECURITY_ROLES: "viewSecurityRoles",
    EDIT_SECURITY_ROLES: "editSecurityRoles"
        
};
